### ISSUE TITLE
[Voting] 是否在库中同时拥有现有方案和纯 ffmpeg 方案

### ISSUE THREAD

**Issue by I-love-study** [I-love-study/py-rotaeno-stablizer-gui#5]
相关issue：https://github.com/I-love-study/py-rotaeno-stablizer-gui/issues/1

已知：
- 在1080P以上时，纯ffmpeg方案会比现有方案强
- 在1080p以下，则现有方案比纯ffmpeg方案弱

纯 ffmpeg 方案：

优点
1. python端可以使用 pillow/skia-python 代替 opencv-python，减小打包体积。
2. 因为python端只用于绘制背景/掩码，所以性能上要求不高。

缺点：
1. 需要解码视频两次（一次获取旋转角，一次正式处理），在低分辨率下，速度比只需解码一次的现有方案慢

现有方案：

优点
1. 只需解码一次，在低分辨率下有优势。

缺点：
1. 受到PIPE传输效率影响，最高速度会被卡死（1080P在75fps上下）
2. 要打包 opencv-python 这个**很有重量**的第三方库

**Comment by Lawrenceeeeeeee** [comment]
直接手搓一个ffmpeg filter？就是工作量有点大（

**Comment by I-love-study** [comment]
> 直接手搓一个ffmpeg filter？就是工作量有点大（

毕竟只是一个只会点 Py 的菜鸡，直接通过其他语言(c/c++/rust)来实现这个对自己还是有点难了。
以前也试过pyav，不过那玩意儿用起来更是难受，也用不了ffmpeg filter之类的。

毕竟遇事不决，ffmpeg（
